# Generated by Django 3.2.13 on 2023-05-24 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
