# Generated by Django 3.2.13 on 2023-05-24 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_movie_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='like_user',
            field=models.ManyToManyField(related_name='like_movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
