# Generated by Django 3.2.13 on 2023-05-24 01:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('action_cnt', models.IntegerField(default=0)),
                ('adventure_cnt', models.IntegerField(default=0)),
                ('animation_cnt', models.IntegerField(default=0)),
                ('comedy_cnt', models.IntegerField(default=0)),
                ('crime_cnt', models.IntegerField(default=0)),
                ('documentary_cnt', models.IntegerField(default=0)),
                ('drama_cnt', models.IntegerField(default=0)),
                ('family_cnt', models.IntegerField(default=0)),
                ('fantasy_cnt', models.IntegerField(default=0)),
                ('history_cnt', models.IntegerField(default=0)),
                ('horror_cnt', models.IntegerField(default=0)),
                ('music_cnt', models.IntegerField(default=0)),
                ('mystery_cnt', models.IntegerField(default=0)),
                ('romance_cnt', models.IntegerField(default=0)),
                ('science_fiction_cnt', models.IntegerField(default=0)),
                ('tv_movie_cnt', models.IntegerField(default=0)),
                ('thriller_cnt', models.IntegerField(default=0)),
                ('war_cnt', models.IntegerField(default=0)),
                ('western_cnt', models.IntegerField(default=0)),
                ('action_key', models.BooleanField(default=False)),
                ('adventure_key', models.BooleanField(default=False)),
                ('animation_key', models.BooleanField(default=False)),
                ('comedy_key', models.BooleanField(default=False)),
                ('crime_key', models.BooleanField(default=False)),
                ('documentary_key', models.BooleanField(default=False)),
                ('drama_key', models.BooleanField(default=False)),
                ('family_key', models.BooleanField(default=False)),
                ('fantasy_key', models.BooleanField(default=False)),
                ('history_key', models.BooleanField(default=False)),
                ('horror_key', models.BooleanField(default=False)),
                ('music_key', models.BooleanField(default=False)),
                ('mystery_key', models.BooleanField(default=False)),
                ('romance_key', models.BooleanField(default=False)),
                ('science_fiction_key', models.BooleanField(default=False)),
                ('tv_movie_key', models.BooleanField(default=False)),
                ('thriller_key', models.BooleanField(default=False)),
                ('war_key', models.BooleanField(default=False)),
                ('western_key', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
